### ISSUE TITLE
Can't sign into Stately in the extension

### ISSUE THREAD

**Issue by UberMouse** [statelyai/xstate-tools#102]
Hi,

I can't get the Sign into VSCode link that gets displayed on the stately website when the extension is trying to sign you in, to actually open VSCode. For some reason it just opens Chrome (not my default browser, the vscode extension opens the stately sign in page in Vivaldi) to the new tab page every time I click it.

I'm on Ubuntu 20.04.4 LTS, i3 window manager and the following VSCode version
![image](https://user-images.githubusercontent.com/693020/157995584-9551f893-4bd3-4910-a426-6b57a95e4572.png)

Let me know if there is any other information I can provide, or steps I can perform to help.

**Comment by mattpocock** [comment]
@UberMouse Hm, this is likely going to be tough for us to diagnose. There might be an issue with how Vivaldi interprets vscode's url scheme?
