### ISSUE TITLE
"open visual editor" does nothing

### ISSUE THREAD

**Issue by macguffin** [statelyai/xstate-tools#105]
Hi when I click "Open Visual Editor" nothing happens. It did work when I first tried it but now doesn't.
If Iook in Log(Window) I get this error:
```
[renderer3] [error] Cannot get password: Error: Cannot get password
    at I.$getPassword (vscode-file://vscode-/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:1522:45602)
```
Do you think it's a corporate proxy issue? 
Any idea how I get get it to work?

"Open Inspector" is working - assuming that doesn't need to go to the stately.ai site.

Thanks

**Comment by mattpocock** [comment]
Hm, this is likely going to be very difficult to emulate from our end. Can you give us some more information?

Does the webview open? (i.e. does another panel open at all?)
Does your browser open?

**Comment by mattpocock** [comment]
Can you potentially film a video of you attempting to open it?
Is there any output from the extension itself? (in Output/XState)

**Comment by macguffin** [comment]
https://user-images.githubusercontent.com/567652/158996707-272a21fa-c16c-4100-b3af-1a452e8aae2e.mov

It feels to me like a corporate proxy or maybe something to do with the extensions authentication with [stately.ai](http://stately.ai/).

The main bit I want is the viewer which is working fine :).

Here is a video, I’ve just switched to VSC from IDEA (mainly because I like your extension so much). If there is anything else I can provide, let me know.

Also weirdly it did seem to work the very first time I tried it, had a pop up etc and then it was in edit mode. 
Have tried re-installing extension, removing it from the user folder etc.

Is there any way to force re-authentication?

Many thanks

**Comment by atroshchenkoff** [comment]
I have exactly the same problem. The first install worked, but then it stopped working. I tried reinstalling the extension, and even completely removed vscode - nothing helped...

**Comment by davidkpiano** [comment]
Added to Linear: https://linear.app/statelyai/issue/STA-1696/clicking-open-in-visual-editor-not-working-for-some-users

**Comment by davidkpiano** [comment]
Do you see any errors in the developer console? See below for how to open the dev tools in VS Code:

![CleanShot 2022-06-20 at 12 18 25@2x](https://user-images.githubusercontent.com/1093738/174643849-8594706d-683c-43c4-a3bb-2002bc72ebed.png)

**Comment by atroshchenkoff** [comment]
![Снимок экрана от 2022-06-20 20-32-23](https://user-images.githubusercontent.com/88941505/174653648-cc37fc24-4eb2-465f-821d-60aaf97802e5.png)

This is what comes out immediately after clicking on the button "Open Visual Editor"

**Comment by UberMouse** [comment]
Looking into this, I see that there appears to be binary data in the string that is being JSON.parsed at the line the stacktrace points to. Which seems to indicate the saved auth data has been corrupted. So I'll sign in and out and that should fix it
