### ISSUE TITLE
VSCode's Extension's usage check doesn't understand choose()

### ISSUE THREAD

**Issue by erikras** [statelyai/xstate-tools#115]
I'm seeing this:

<img width="527" alt="Screen Shot 2022-03-18 at 2 59 19 PM" src="https://user-images.githubusercontent.com/4396759/159016859-6ec4fbc8-047c-4ae9-bfb7-80bc2b5a0b26.png">

...when I _am_ using the action inside an `actions.choose()` like this:

<img width="353" alt="Screen Shot 2022-03-18 at 2 59 45 PM" src="https://user-images.githubusercontent.com/4396759/159016808-e9bc5382-6194-4e6a-a9a9-dd82e71d2bc0.png">

Seems like a bug?

**Comment by Andarist** [comment]
It seems so 😉

**Comment by erikras** [comment]
TypeScript is also unhappy. I guess it's a TS error, actually.

**Comment by mattpocock** [comment]
Duplicate of #70
