### ISSUE TITLE
Typegen breaks when a state or a tag contains single quotes

### ISSUE THREAD

**Issue by Devessier** [statelyai/xstate-tools#116]
First, I want to say I admire the work you did on Typegen, it's a really amazing feature!
I've been trying to use it on machines that contain single quotes in states and tags and it made typegen break.

The error occurred with Stately VSCode extension, and with the CLI, which gave me more information about the reason of the fail:

<img width="1307" alt="CleanShot 2022-03-20 at 12 41 03@2x" src="https://user-images.githubusercontent.com/29370468/159160515-b7d2fa25-defe-40b1-b5c3-79207d56c4c8.png">

I made a reproduction for both states and tags: https://github.com/Devessier/xstate-typegen-quotes-issue-repro.

Let me know if you need more information.
Have a nice day!

**Comment by Andarist** [comment]
Thanks for the report and the repro case. It seems like a straightforward fix - gonna handle it asap.
