### ISSUE TITLE
Bug: typegen fails if there's a single quote in a guard

### ISSUE THREAD

**Issue by erikras** [statelyai/xstate-tools#127]
I've got this guard called `"It's Play Time"`, and the typegen falls over unless I remove the apostrophe. 😃

**Comment by davidkpiano** [comment]
Workaround:

```diff
-cond: "It's Play Time"
+cond: "It Is Play Time"
```

**Comment by mattpocock** [comment]
I thought we'd fixed this! Interesting...

**Comment by erikras** [comment]
C'mon, @davidkpiano. @mattpocock seems theatre adjacent enough to agree with me that you can't say "It is showtime!" 🙄 🎭

**Comment by Andarist** [comment]
This issue has only been fixed for tags and state names in this PR: https://github.com/statelyai/xstate-tools/pull/118

Gonna prepare a PR to fix this in guards too.

**Comment by mattpocock** [comment]
"Theatre adjacent" is going on my gravestone
