### ISSUE TITLE
Extension throws exception and stops working on type only imports

### ISSUE THREAD

**Issue by jramstedt** [statelyai/xstate-tools#137]
Importing type only imports causes exception.

Example:
import { type AnyEventObject, createMachine } from 'xstate'

Result:
unknown: Unexpected token, expected "," (1:14) > 1 | import { type AnyEventObject, createMachine } from 'xstate' | ^ 2 | import { pixi } from './main' 3 | 4 | import type { Menu } from './ui/menu'

**Comment by mattpocock** [comment]
This looks like incorrect syntax to me:

`import type { AnyEventObject, createMachine } from 'xstate'` is correct

**Comment by jramstedt** [comment]
It is correct syntax with TypeScript 4.5.

https://www.typescriptlang.org/docs/handbook/release-notes/typescript-4-5.html

**Comment by jramstedt** [comment]
@mattpocock 
Your example isn't correct. Since you can't import createMachine as type.

**Comment by mattpocock** [comment]
Here's a CSB of my example working and yours failing:

https://codesandbox.io/s/upbeat-aryabhata-ur6f7g?file=/src/index.ts:0-148

**Comment by jramstedt** [comment]
I don't really understand what that link proves.

The syntax is correct with TypeSccript 4.5. I have been using it for a long time and you can yourself check it from the documentation.

There is a workaround for this problem with two import lines:

import { createMachine } from 'xstate'
import type { AnyEventObject } from 'xstate'

But, I would like for the extension to support this import syntax.

**Comment by Andarist** [comment]
Yeah, you are right @jramstedt, if possible this should be supported. When dealing with a lot of reported issues it's easy sometimes to misinterpret the reported issue.

**Comment by mattpocock** [comment]
@jramstedt TIL! 

![image](https://user-images.githubusercontent.com/28293365/164729654-b55a2b22-699a-4c25-aa7f-2781678129d7.png)

Thanks for your patience, we'll get this fixed.
