### ISSUE TITLE
Typescript error on changing context argument to _ in actions

### ISSUE THREAD

**Issue by searchableguy** [statelyai/xstate-tools#172]
If I change first argument's name to `_` to suppress unused variable warning/error from typescript, I get this error. 

![image](https://user-images.githubusercontent.com/73341821/176758269-967d16e4-0ea5-4216-abd1-4fc7459d4a3f.png)

```
Type '(_: CheckoutMachineContext, event: SelectLockEvent) => LockState' is not assignable to type 'LockState | PartialAssigner<{ lock: LockState; }, SelectLockEvent, "lock"> | undefined'.
  Type '(_: CheckoutMachineContext, event: SelectLockEvent) => LockState' is not assignable to type 'PartialAssigner<{ lock: LockState; }, SelectLockEvent, "lock">'.
    Types of parameters '_' and 'context' are incompatible.
      Type '{ lock: LockState; }' is missing the following properties from type 'CheckoutMachineContext': paywallConfig, payment, quantity, recipientsts(2322)
checkoutMachine.ts(368, 15): Did you mean to call this expression?
```

**Comment by Andarist** [comment]
Please always try to share a repro case in a runnable form - either by providing a git repository to clone or a codesandbox.

**Comment by Andarist** [comment]
I'm going to close this as part of cleaning up issues for housekeeping purposes. However, please don't hesitate to respond back here or in another issue - I will reopen this if you provide a repro case.
