### ISSUE TITLE
[Bug] Custom guard act as if never used

### ISSUE THREAD

**Issue by astahmer** [statelyai/xstate-tools#18]
**Problem:** 
getting a `xxx is never used in the machine definition` when using custom guards (https://xstate.js.org/docs/guides/guards.html#custom-guards)

**Context:**
Using the VS-code extension version `1.2.1` and `xstate` version `4.23.0`.

**Repro:**
When pasting this in the parser (https://xstate-parser-example-site.vercel.app) :

```ts
createMachine(
    {
        initial: "start",
        states: {
            start: {
                on: {
                    MOVE: [
                        { target: "end", cond: { type: "customGuard", param: 123 } },
                        { target: "end", cond: "workingGuard" },
                    ],
                },
            },
            end: {},
        },
    },
    { guards: { customGuard: (ctx) => false, workingGuard: (ctx) => true } }
);
```

We can see that the custom guard is noted as `anonymous`

**Comment by Silverwolf90** [comment]
In the context of typegen, the lack of this support for this leads to type errors. lt would be preferable to even generate `any` or `unknown` until it's properly supported.

<img width="732" alt="image" src="https://user-images.githubusercontent.com/1631625/162047026-5f165d30-ee3d-4285-b2ba-2e0ce6325bc9.png">

**Comment by CodingDive** [comment]
This is a big issue with the typegen currently as any custom guard will not appear in the typegen file. cc @mattpocock 

Also came up in discord https://discord.com/channels/795785288994652170/1001836095253790793
