### ISSUE TITLE
Machine ID is truncated when I open the machine in the visual editor

### ISSUE THREAD

**Issue by laurakalbag** [statelyai/xstate-tools#194]
https://www.loom.com/share/41c04fbafb964d5091e036dc53afa301

**Comment by Andarist** [comment]
The most likely culprit is the fact that the code lens command embeds the possibly outdated arguments:
https://github.com/statelyai/xstate-tools/blob/53ba81ba15f991952f220c0b519225328f06b9f4/apps/extension/server/src/server.ts#L164-L173

The fix would be to limit the arguments and grab the config "on demand", when the user actually clicks on the code lens. This way we'd guarantee that we grab the most up-to-date config etc

**Comment by Andarist** [comment]
We can't be completely sure as we never confirmed what has causes this issue but I strongly believe that there is non-zero chance that this is being fixed by: https://github.com/statelyai/xstate-tools/pull/220
