### ISSUE TITLE
VSS extension randomly throw error: Could not find a machine at the current cursor.

### ISSUE THREAD

**Issue by nlk-jan** [statelyai/xstate-tools#200]
Hi, 
I am very new to Xstate so apologize for the noob question. 
I cannot get Xstate VSS plugin to open Stately Visualiser reliably.  It randomly appears once or twice (over createMachine), but later it is not showing, and I am getting an error: Could not find a machine at the current cursor.
Thanks
Jan

**Comment by Andarist** [comment]
There is a good chance that the underlying issue is similar to this one https://github.com/statelyai/xstate-tools/issues/194
