### ISSUE TITLE
Editing a machine visually can result in information being lost in the code

### ISSUE THREAD

**Issue by jamesbvaughan** [statelyai/xstate-tools#211]
I have a machine that I edit both directly in the code and in the visual editor in the VS Code extension.

After editing the machine via the visual editor, the following are removed from the machine source:
- comments
- state metadata (I see that this is tracked in https://github.com/statelyai/xstate-tools/issues/104)
- [forbidden transitions](https://github.com/statelyai/xstate-tools/issues/104)

Here is a simple machine that demonstrates these issues:
```typescript
import { createMachine } from "xstate";

createMachine({
  id: "example",
  initial: "first",
  states: {
    first: {
      meta: {
        example: "example",
      },
      on: {
        next: {
          target: "second",
        },
      },
    },
    // This is a comment
    second: {
      on: {
        next: {
          target: "third",
        },
        backToFirst: undefined,
      },
    },
    third: {},
  },
  on: {
    backToFirst: {
      target: ".first",
    },
  },
});
```

Here is a diff showing the changes made to this machine by simply opening up the visual editor (and running `prettier`):
```diff
 import { createMachine } from "xstate";

+/** @xstate-layout N4IgpgJg5mDOIC5RgB4EMC2AHANmAdAGYCWATrAC4DEAdqhYqFgPazEXHM2MgqIBMANgCM+YQFZBQgCwBOAMzz+wgAzyA7ABoQAT0Szx+cSpPjh82QA4VQxQF8721JlwFYYAMZcItejxZsHFw8fAjS4vz4guqy6hHqlgqW0pbaeggGRiYqZhbWtvIOTujYeFQARmgeANYAKswAYmSU-qzsnNxIvIjS-Gn6hsam5lY2gvZFIDTMEHA8zqUEJOQMXQHtwV2hwurqUZJCKuqC4vmpuvoq+NkqgqPSR1Kykwuu+O5eNBCtgR0hiPJpIIjAlhCJhDtxEo1P0MlcbrYFKdVJYXiU3hQABZkb5rNpBTqgUJQyxiFRglKxDS3cSw2Tw7KI+TIlSoxzgdF4H4bQndBDCc7pQQOBxAA */
 createMachine({
   id: "example",
   initial: "first",
   states: {
     first: {
-      meta: {
-        example: "example",
-      },
       on: {
         next: {
           target: "second",
         },
       },
     },
-    // This is a comment
     second: {
       on: {
         next: {
           target: "third",
         },
-        backToFirst: undefined,
       },
     },
     third: {},
```

In the case of `meta` values, the linter does warn that they're incompatible with the visual editor, which is nice, but in the cases of comments and forbidden transitions, this behavior was surprising and frustrating.

**Comment by Andarist** [comment]
I'm working on improving exactly this stuff. Thanks for raising the case of the forbidden transitions - it's an additional scenario I will keep in mind.

**Comment by astahmer** [comment]
hey, amazing work so far on the editor, congratz !

I do have one little issue, kinda related to this one I guess: I liked the concise lines format on the left, it made reading the machine config easier for me personally, would it be possible to keep it this way ?

<img width="1070" alt="Screenshot 2022-11-05 at 18 13 05" src="https://user-images.githubusercontent.com/47224540/200132762-189f06ca-4362-4b1c-ad77-a45ec1c247bf.png">

also, not so related, would you consider adding a "Save" button in the VSCode extension so that only when it is submitted the `machine.ts` file will actually be saved ? (so that I can undo easily if needed)
