### ISSUE TITLE
Transitions from same node all on top of each other (Visual Editor VS Code plugin)

### ISSUE THREAD

**Issue by andrebernardini** [statelyai/xstate-tools#227]
Steps to reproduce

1. Create a statemachine that has multiple transitions (with different guards) starting from node 1
2. Arrange them nicely with the visual editor
3. Safe the file that contains the machine in vscode

Expected outcome: The layout that was configured in step 2 should be preserved
![image](https://user-images.githubusercontent.com/66627490/195847361-122feaba-e7c0-47e3-bc42-86286eaf2d20.png)
Actual outcome: All transitions that start from the same node are arranged on top of each other
![image](https://user-images.githubusercontent.com/66627490/195847680-1c16b1bd-4558-4cac-bac5-9bcfa704ca64.png)

**Comment by davidkpiano** [comment]
I'm currently looking into this 🔍

**Comment by Andarist** [comment]
I wonder - have you tried pressing the autolayout button? It would be good to confirm if this is caused by a broken autolayout string (or incorrect handling of that in the Studio) or if it's caused by the autolayout itself.

**Comment by andrebernardini** [comment]
Wow - that's some superquick reactions here!

In my first try, autolayout was involved yes.

However: I also removed the layout-string competely, then dragged the layout as I wanted to have it and then hit ctrl-s in vscode --> Same effect. So I doubt that autolayout has something to do with it.

**Comment by davidkpiano** [comment]
> Wow - that's some superquick reactions here!
> 
> In my first try, autolayout was involved yes.
> 
> However: I also removed the layout-string competely, then dragged the layout as I wanted to have it and then hit ctrl-s in vscode --> Same effect. So I doubt that autolayout has something to do with it.

Speaking of super quick, this is now in PR review. The issue was in how we were serializing edges.

**Comment by davidkpiano** [comment]
This has been fixed (3 days ago)! 🔧
