### ISSUE TITLE
Extension only rewrites the typegen import path is the base filename is wrong

### ISSUE THREAD

**Issue by programbo** [statelyai/xstate-tools#230]
https://www.loom.com/share/dae3de3b3d9a41d094acc5b507cc5e31

The complete import path to the typegen file should either be validated OR rewritten whenever the file is updated.

Currently, if I move the typegen file and VS Code conveniently updates the import path for me, the extension creates and updates a new sibling typegen file but the source of truth for typings will continue to be the moved file (that is no longer being updated).

The extension only rewrites the import path of the base file name of the typegen file does not match the working file.

e.g. In `smarty.machine.ts`...

✅  `tsTypes: {} as import("./blarty.machine.typegen").Typegen0` 👉🏼 `"./smarty.machine.typegen"`

❌ `tsTypes: {} as import("../smarty.machine.typegen").Typegen0` is valid

**Comment by Andarist** [comment]
I've rechecked this scenario with my latest changes (not published yet) and I believe that this is being fixed by [this PR](https://github.com/statelyai/xstate-tools/pull/220)
