### ISSUE TITLE
editing statechart in the vscode extension removes the context binding via the data attribute for Invoking Services

### ISSUE THREAD

**Issue by XantreGodlike** [statelyai/xstate-tools#238]
Before i moved a card at statechart
![image](https://user-images.githubusercontent.com/57757211/200774711-4e7832d2-b21b-4583-a1cc-0c38373e5a9a.png)
After I moved a card at statechart (data prop removed)
![image](https://user-images.githubusercontent.com/57757211/200774825-f6679b21-7612-400e-8ed1-cc8b563d40cf.png)

**Comment by Andarist** [comment]
We are working on fixing this - the PR is already available here: https://github.com/statelyai/xstate-tools/pull/229

**Comment by XantreGodlike** [comment]
Cool. When it will be merged?)
