### ISSUE TITLE
Vs code extension for xstate - can I export the image

### ISSUE THREAD

**Issue by FriendlyUser** [statelyai/xstate-tools#247]
Hello, love using xstate.

I am wondering if there is any way to export the state machine diagram in vscode to an image or to xstate visualizer on web.

Let me know if you need clarification.

**Comment by Andarist** [comment]
There is no such feature right now but it's a good idea. This might come in the future.

**Comment by karfau** [comment]
I'm all for it, and this would also be really awesome as a command for the CLI.

And if possible offer SVG in addition to PNG.

**Comment by davidkpiano** [comment]
Feel free to vote/comment here: https://statelyai.canny.io/admin/feedback/editor/p/export-to-svgpng

Closing this as it's covered in the above feature request 🗳️
