### ISSUE TITLE
Visual Editor asks to log in Stately, Google Connect raises a 403

### ISSUE THREAD

**Issue by hchauvat** [statelyai/xstate-tools#249]
Hi, 

Following the update of the VSCode extension to 1.10.0, when opening the Visual Editor, I'm being asked to log in Stately. But when I click on the "Connect with Google" button, I get a 403.

I tried reinstalling the extension and made sure I was able to log in that way in a standard browser (Brave and Chome).

https://user-images.githubusercontent.com/59441901/202673088-8d41e2e8-778e-4142-bdb8-ea10686d7530.mov

EDIT: I also tried logging with GitHub but the view remains empty

**Comment by mellson** [comment]
Hi @hchauvat thank you for the issue. Sorry about the trouble, we did just have a slight error in one of our deploys. Can you check how it works now?

**Comment by hchauvat** [comment]
@mellson it does! Thanks a lot :)

**Comment by mellson** [comment]
> @mellson it does! Thanks a lot :)

Great to hear; thank you!
