### ISSUE TITLE
version 1.11.0 typegen broken on windows, works on mac.

### ISSUE THREAD

**Issue by theslantedroom** [statelyai/xstate-tools#265]
Good day, just upgraded to 1.11.0 on my windows machine and had the following issue:

the typegen file apears to generate incorrectly.  The result was typescript errors in the app.

![xstate vscode 1 11 0 windows](https://user-images.githubusercontent.com/73557008/206046851-66c6beb4-eb04-47d0-8388-eb9bb5fbcd44.png)

You will notice the missingImplementations and eventsCausingServices were generated differently.
This is not the case on mac / Xstate vs code extention 1.11.0

Temp fix:  downgrading to 1.10.0 and I am back in business.

**Comment by Andarist** [comment]
Hmm, this is quite weird - especially that you mention this being specific to the operating system. Any chance that you would be able to provide a repro case? I have no idea how to start investigating this without one

**Comment by theslantedroom** [comment]
I may be able to. Let me see what I can do.  Additionally, I confirmed this to be the case on two different PCs.

**Comment by Andarist** [comment]
I think I've found the issue and I'm working on the fix [here](https://github.com/statelyai/xstate-tools/pull/267). However, this problem doesn't quite relate to the OS - so there is still a minimal chance that your issue here is different somehow.

**Comment by theslantedroom** [comment]
https://user-images.githubusercontent.com/73557008/206540686-6e1dbf48-32e6-46d7-9125-68b7fc555152.mp4

I have created a simple repo for you with a working (bug exists) example 

https://github.com/theslantedroom/XstateTypeGenBug1.11.0

**Comment by nomoon** [comment]
I believe I've just had this occur on Mac, using the latest VS Code and XState extension. I opened a previously-working machine file, I guess the Typegen re-processed, and suddenly I have  errors, with this in my typegen:

```typescript
  missingImplementations: {
    actions: "j6k8t"; // <-- that's not a real action!
    delays: never;
    guards: never;
    services: never;
  };
```

Glad to hear a fix is in the works!
