### ISSUE TITLE
I used to see the name of the actions in the diagram, why is not showing anymore?

### ISSUE THREAD

**Issue by nicoPPLSI** [statelyai/xstate-tools#278]
By any chance do you know why I see these "ids" instead of the names? It used to work but I can't see it anymore

![image](https://user-images.githubusercontent.com/108067329/207629297-e5d48f43-27c2-4cf7-8a8f-7ef0a30a5e6f.png)

**Comment by davidkpiano** [comment]
cc. @Andarist

**Comment by Andarist** [comment]
@nicoPPLSI could you share your machine config with us?

**Comment by nicoPPLSI** [comment]
@Andarist 

I don't know exactly what you mean, but maybe is this?

`createMachine<
  iCartCheckoutMachineContext,
  CartCheckoutEventsType,
  CartCheckoutStates
>({
  context: {
    userId: 'lspro',
    retries: 3,
    isLoading: true,
    error: '',
    membershipCards: [],
    membershipCardRefs: [],
    associateInfo: null,
    selectedCardsIndex: [],
    selectedPlansAmount: 0,
    oneTimeFee: 0,
  },
  id: 'cartCheckout',
  initial: 'chooseMembership',
  states: {
    landingPage: {
      type: 'atomic',
      on: {
        GET_STARTED: {
          target: 'chooseMembership',
        },
      },
    },
    chooseMembership: {
      type: 'compound',
      initial: 'loading',
      states: {
        loading: {
          type: 'compound',
          initial: 'init',
          states: {
            init: {
              on: {
                SET_ASSOCIATE_ID: [
                  {
                    cond: (ctx, event) => !!event.associateId,
                    actions: assign({ userId: (ctx, event) => event.associateId }),
                    target: 'loadingAssociateDetails',
                  },
                  {
                    actions: assign({
                      error: (ctx, error) => {
                        'No associate id found, add and try again!';
                      },
                    }),
                    target: '#cartCheckout.chooseMembership.failure',
                  },
                ],
              },
            },
            loadingAssociateDetails: {
              invoke: {
                src: 'fetchAssociateDetails',
                onDone: [
                  {
                    cond: (ctx, event) => event.data?.accessControl,
                    target: 'loadingMembershipDetails',
                    actions: assign({
                      associateInfo: (ctx, event) => event.data,
                    }),
                  },
                  {
                    actions: assign({
                      error: (ctx, event) =>
                        !event.data
                          ? { message: 'Associate detail not found!' }
                          : !event.data?.accessControl
                          ? { message: 'Associate has no access control' }
                          : { message: '' },
                    }),
                    target: '#cartCheckout.chooseMembership.failure',
                  },
                ],
                onError: [
                  {
                    target: '#cartCheckout.chooseMembership.failure',
                    actions: assign({ error: (ctx, event) => event.data }),
                  },
                ],
              },
            },
            loadingMembershipDetails: {
              invoke: {
                src: 'fetchMembershipDetails',
                onDone: [
                  {
                    cond: (ctx, event) => event.data,
                    actions: assign((context, event) => {
                      const membershipCards: membershipCardInterface[] = event.data;
                      const membershipCardRefs = membershipCards.map((card, index) =>
                        spawn(
                          planCardMachine({
                            index,
                            id: card.id,
                            name: card.name,
                            description: card.description,
                            price: +card.details.price,
                            planType: getPlanType(
                              card.details.plan_category.plan_type,
                              card.details.plan_category.plan_short_name,
                            ),
                            selected: false,
                            disabledBy: [],
                          }),
                          `membershipPlan${card.id}`,
                        ),
                      );
                      return {
                        ...context,
                        membershipCards,
                        membershipCardRefs,
                      };
                    }),
                    target: '#cartCheckout.chooseMembership.loaded',
                  },
                  {
                    actions: assign({
                      error: (ctx, error) => {
                        'Error happened while fetching membership details';
                      },
                    }),
                    target: '#cartCheckout.chooseMembership.failure',
                  },
                ],
                onError: {
                  target: '#cartCheckout.chooseMembership.failure',
                  actions: assign({ error: (ctx, event) => event.data }),
                },
              },
            },
          },
        },
        loaded: {
          initial: 'idle',
          entry: assign({ isLoading: false }),
          states: {
            idle: {
              on: {
                SELECT: {
                  actions: [
                    assign((context, event) => {
                      const selectedCardsIndex = context.selectedCardsIndex.concat(event.id);

                      return {
                        ...context,
                        selectedCardsIndex,
                      };
                    }),
                    (ctx, event) =>
                      ctx.membershipCardRefs.forEach((ref) =>
                        ref.send({ type: 'UPDATE', clickedOnPlanType: event.planType }),
                      ),
                  ],
                  target: 'calculatingCost',
                },
                UNSELECT: [
                  {
                    actions: [
                      assign((context, event) => {
                        const selectedCardsIndex = context.selectedCardsIndex.filter((card) => card !== event.id);

                        return {
                          ...context,
                          selectedCardsIndex,
                        };
                      }),
                      send((ctx, event) => ({ type: 'UNSELECTED' }), {
                        to: (ctx, event) => `membershipPlan${event.id}`,
                      }),
                      (ctx, event) =>
                        ctx.membershipCardRefs.forEach((ref) =>
                          ref.send({ type: 'RESET', clickedOnPlanType: event.planType }),
                        ),
                    ],
                    target: 'calculatingCost',
                  },
                ],
              },
            },
            calculatingCost: {
              invoke: {
                src: 'calculateCost',
                onDone: [
                  {
                    actions: assign((context, event) => {
                      return {
                        ...context,
                        selectedPlansAmount: event.data,
                      };
                    }),
                    target: 'idle',
                  },
                ],
                onError: {},
              },
            },
          },
        },
        failure: {
          on: {
            RETRY: {
              target: 'loading',
            },
          },
        },
      },
    },
  },
});`

**Comment by nicoPPLSI** [comment]
@Andarist

I don't know exactly what you mean, but maybe is this?

```
createMachine<
  iCartCheckoutMachineContext,
  CartCheckoutEventsType,
  CartCheckoutStates
>({
  context: {
    userId: 'lspro',
    retries: 3,
    isLoading: true,
    error: '',
    membershipCards: [],
    membershipCardRefs: [],
    associateInfo: null,
    selectedCardsIndex: [],
    selectedPlansAmount: 0,
    oneTimeFee: 0,
  },
  id: 'cartCheckout',
  initial: 'chooseMembership',
  states: {
    landingPage: {
      type: 'atomic',
      on: {
        GET_STARTED: {
          target: 'chooseMembership',
        },
      },
    },
    chooseMembership: {
      type: 'compound',
      initial: 'loading',
      states: {
        loading: {
          type: 'compound',
          initial: 'init',
          states: {
            init: {
              on: {
                SET_ASSOCIATE_ID: [
                  {
                    cond: (ctx, event) => !!event.associateId,
                    actions: assign({ userId: (ctx, event) => event.associateId }),
                    target: 'loadingAssociateDetails',
                  },
                  {
                    actions: assign({
                      error: (ctx, error) => {
                        'No associate id found, add and try again!';
                      },
                    }),
                    target: '#cartCheckout.chooseMembership.failure',
                  },
                ],
              },
            },
            loadingAssociateDetails: {
              invoke: {
                src: 'fetchAssociateDetails',
                onDone: [
                  {
                    cond: (ctx, event) => event.data?.accessControl,
                    target: 'loadingMembershipDetails',
                    actions: assign({
                      associateInfo: (ctx, event) => event.data,
                    }),
                  },
                  {
                    actions: assign({
                      error: (ctx, event) =>
                        !event.data
                          ? { message: 'Associate detail not found!' }
                          : !event.data?.accessControl
                          ? { message: 'Associate has no access control' }
                          : { message: '' },
                    }),
                    target: '#cartCheckout.chooseMembership.failure',
                  },
                ],
                onError: [
                  {
                    target: '#cartCheckout.chooseMembership.failure',
                    actions: assign({ error: (ctx, event) => event.data }),
                  },
                ],
              },
            },
            loadingMembershipDetails: {
              invoke: {
                src: 'fetchMembershipDetails',
                onDone: [
                  {
                    cond: (ctx, event) => event.data,
                    actions: assign((context, event) => {
                      const membershipCards: membershipCardInterface[] = event.data;
                      const membershipCardRefs = membershipCards.map((card, index) =>
                        spawn(
                          planCardMachine({
                            index,
                            id: card.id,
                            name: card.name,
                            description: card.description,
                            price: +card.details.price,
                            planType: getPlanType(
                              card.details.plan_category.plan_type,
                              card.details.plan_category.plan_short_name,
                            ),
                            selected: false,
                            disabledBy: [],
                          }),
                          `membershipPlan${card.id}`,
                        ),
                      );
                      return {
                        ...context,
                        membershipCards,
                        membershipCardRefs,
                      };
                    }),
                    target: '#cartCheckout.chooseMembership.loaded',
                  },
                  {
                    actions: assign({
                      error: (ctx, error) => {
                        'Error happened while fetching membership details';
                      },
                    }),
                    target: '#cartCheckout.chooseMembership.failure',
                  },
                ],
                onError: {
                  target: '#cartCheckout.chooseMembership.failure',
                  actions: assign({ error: (ctx, event) => event.data }),
                },
              },
            },
          },
        },
        loaded: {
          initial: 'idle',
          entry: assign({ isLoading: false }),
          states: {
            idle: {
              on: {
                SELECT: {
                  actions: [
                    assign((context, event) => {
                      const selectedCardsIndex = context.selectedCardsIndex.concat(event.id);

                      return {
                        ...context,
                        selectedCardsIndex,
                      };
                    }),
                    (ctx, event) =>
                      ctx.membershipCardRefs.forEach((ref) =>
                        ref.send({ type: 'UPDATE', clickedOnPlanType: event.planType }),
                      ),
                  ],
                  target: 'calculatingCost',
                },
                UNSELECT: [
                  {
                    actions: [
                      assign((context, event) => {
                        const selectedCardsIndex = context.selectedCardsIndex.filter((card) => card !== event.id);

                        return {
                          ...context,
                          selectedCardsIndex,
                        };
                      }),
                      send((ctx, event) => ({ type: 'UNSELECTED' }), {
                        to: (ctx, event) => `membershipPlan${event.id}`,
                      }),
                      (ctx, event) =>
                        ctx.membershipCardRefs.forEach((ref) =>
                          ref.send({ type: 'RESET', clickedOnPlanType: event.planType }),
                        ),
                    ],
                    target: 'calculatingCost',
                  },
                ],
              },
            },
            calculatingCost: {
              invoke: {
                src: 'calculateCost',
                onDone: [
                  {
                    actions: assign((context, event) => {
                      return {
                        ...context,
                        selectedPlansAmount: event.data,
                      };
                    }),
                    target: 'idle',
                  },
                ],
                onError: {},
              },
            },
          },
        },
        failure: {
          on: {
            RETRY: {
              target: 'loading',
            },
          },
        },
      },
    },
  },
});
```

**Comment by Andarist** [comment]
I think that my PR here fixes this: https://github.com/statelyai/xstate-tools/pull/280 . Although, to the best of my understanding - those particular things were previously displayed in the Editor as "Inline" (and that's how I'm fixing it)

**Comment by nicoPPLSI** [comment]
> I think that my PR here fixes this: #280 . Although, to the best of my understanding - those particular things were previously displayed in the Editor as "Inline" (and that's how I'm fixing it)

Hi! thanks for your reply.
is there something I can do to fix my problem, I couldn't find a way to fix it in the PR you linked, I don't know exactly what to do with that information, any help is welcome, thanks

**Comment by Andarist** [comment]
Please wait till we merge that PR and release it - then you are going to be able to install the new version from the marketplace and you will be able to confirm if the whole issue got fixed for you.

**Comment by nicoPPLSI** [comment]
thanks @Andarist 
I don't know how to create an alert for when it gets merged, is there a way to do that? I don't think so right? In that case, when is the merging going to take place (ball park) 1/2/3/4 week(s)? just wondering so I can keep an eye on it

**Comment by Andarist** [comment]
It’s already released: https://github.com/statelyai/xstate-tools/releases/tag/stately-vscode%401.11.2
