### ISSUE TITLE
feature: open editor and inspector in active tab group settings

### ISSUE THREAD

**Issue by jlarmstrongiv** [statelyai/xstate-tools#290]
# Overview

In the Xstate VSCode extension, add a new setting called `View Column` with the options `Beside` and `Active`.  

Currently, Xstate always opens or creates a new column beside the current code, which is not usable on small screens or when split-screening.  Letting users specify the active column by default will prevent file tab reshuffling every time I use the Xstate VSCode extension.

## Beside

The default option is `Beside`, which the extension uses by default to open the editor and inspector in the column beside to the current file, creating the column if it does not exist.  Pictured here:

<img width="1648" alt="image" src="https://user-images.githubusercontent.com/20903247/213643248-c4de58c7-8056-4f3e-b772-f96c3970d57d.png">

## Active

The new option is `Active`, which the extension uses to open the editor and inspector in the active column as a file next to the current file.  No columns will be created and VSCode will always use the current column.  Pictured here:

<img width="1648" alt="image" src="https://user-images.githubusercontent.com/20903247/213643357-e28a8323-1548-4537-86c0-cb6f48c15e76.png">

---

### Options

Currently, the setting is hardcoded as [`vscode.ViewColumn.Beside`](https://github.com/statelyai/xstate-tools/blob/main/apps/extension/client/src/initiateEditor.ts#L106).  The docs describe [`vscode.ViewColumn.Active`](https://vshaxe.github.io/vscode-extern/vscode/ViewColumn.html).

### Settings

The settings are described in the [`package.json`](https://github.com/statelyai/xstate-tools/blob/main/apps/extension/client/package.json#L60) file. 

The easiest way to add reference the new setting is to add it to [`XStateConfiguration`](https://github.com/statelyai/xstate-tools/blob/main/apps/extension/client/src/typeSafeVsCode.ts#L19) and reference it as `typeSafeVsCode.getConfiguration('View Column') ?? 'Active';`

### Other

While I do not currently know how to test the changes, I will create a base PR if the xstate team is interested in this contribution.

**Comment by Andarist** [comment]
> While I do not currently know how to test the changes, I will create a base PR if the xstate team is interested in this contribution.

PRs like this are definitely welcome :)

**Comment by jlarmstrongiv** [comment]
@Andarist created a PR for you https://github.com/statelyai/xstate-tools/pull/291
