### ISSUE TITLE
Bug: Inline actions do not inherit any context or event from the machine using Typegen

### ISSUE THREAD

**Issue by xylophonehero** [statelyai/xstate-tools#299]
### Description

When using inline actions with typegen, the type parameters for the action creator functions aren't always inherited.

### Expected result

When using say `assign` inline, then it should look like `assign<MachineContext, TEvent>` wtih the machine's context and current event that triggered that action.

### Actual result

But instead, we just get the defaults for the type parameters `assign<unknown, EventObject>`

### Reproduction

https://github.com/xylophonehero/xstate-log

### Additional context

We can always specify the type params of the actions `log<ToggleContext, EventObject>((ctx)=> ctx.count),` but shouldn't need to do this 😄

**Comment by with-heart** [comment]
@davidkpiano ye, I experienced this just yesterday. I'll create a repro
