### ISSUE TITLE
xstate no loading with vscode 1.45

### ISSUE THREAD

**Issue by veeramarni** [statelyai/xstate-tools#303]
It is not showing in the installation list as, well.

**Comment by davidkpiano** [comment]
It's showing up for 1.75, can you try again?

![CleanShot 2023-02-13 at 09 51 42@2x](https://user-images.githubusercontent.com/1093738/218490856-24aab655-859e-4052-b621-2220a8b0f773.png)

**Comment by veeramarni** [comment]
as you see, we cannot install it in the latest vscode version.
