### ISSUE TITLE
Bug: VSCode extension visual editor can't deal with unrelated `satisfies` keyword

### ISSUE THREAD

**Issue by mihi314** [statelyai/xstate-tools#336]
Typescript 4.9 introduces the [`satisfies` operator](https://www.typescriptlang.org/docs/handbook/release-notes/typescript-4-9.html#the-satisfies-operator). If it is present anywhere in a file that also has a state machine, the visual editor is unable to save any changes.

#### Example file:
```typescript
import { createMachine } from 'xstate';

const machine = createMachine({
  initial: 'waiting',
  states: {
    waiting: {},
  },
});

const unrelatedObjectLiteral = {
  a: true,
  b: false,
} satisfies Record<string, boolean>;
```

#### The error I get:
```
[error] Error: Request applyMachineEdits failed with message: did not recognize object of type "TSSatisfiesExpression"
    at handleResponse (/home/michi/.vscode/extensions/statelyai.stately-vscode-1.14.2/dist/index.js:76778:40)
    at processMessageQueue (/home/michi/.vscode/extensions/statelyai.stately-vscode-1.14.2/dist/index.js:76616:13)
    at Immediate.<anonymous> (/home/michi/.vscode/extensions/statelyai.stately-vscode-1.14.2/dist/index.js:76602:11)
    at process.processImmediate (node:internal/timers:466:21)
```

#### Versions:
* XState VSCode: 1.14.2
* VSCode: 1.77.3
* Typescript: 4.9.5

**Comment by Andarist** [comment]
Currently we are blocked by https://github.com/benjamn/recast/issues/1281 . Since we have some other problems with `recast`, we plan to rewrite this part of the code and drop the dependency on that package.

**Comment by Andarist** [comment]
@benjamn thanks for letting us know about this release ❤️

**Comment by mihi314** [comment]
Sweet, thank you both!
