### ISSUE TITLE
(Feature Request) Use existing layout engine for autolayout

### ISSUE THREAD

**Issue by liam-nt** [statelyai/xstate-tools#407]
In both studio and vscode visual editor, using Autolayout on a machine with 30+ states makes the layout unintelligible and loses the linear layout of the states. Transitions are stacked on top of eachother and can't be made sense of without significant manual re-routing.

Using a layout engine like [Dagre](https://github.com/dagrejs/dagre), [Elk](https://github.com/kieler/elkjs), or [Tala](https://github.com/terrastruct/TALA) would be a big improvement.

**Comment by davidkpiano** [comment]
We do use Elk, and we actually have some major improvements for autolayout coming soon.
