### ISSUE TITLE
Throttle configuration for typegen autosave 

### ISSUE THREAD

**Issue by slowselfip** [statelyai/xstate-tools#42]
With the new typegen feature the extension is doing some "throttled auto save as you type". This can get a bit heavy on the CPU if there's for example a dev-server running in the background watching files and doing recompiles.

Not exactly sure what the best solution would be, but if it would be possible to make the auto save feature configurable that could help.

A workaround is to close any file watchers whilst editing the machine config.

And I must say that the typegen support is probably the biggest leap in developer experience I've ever encountered! Really impressed with what you've achieved. Great work!

**Comment by mattpocock** [comment]
Thank you @slowselfip! My plans are to add a configuration option to VSCode that would let you choose between:

Typegen running on throttle (allows for very quick TS updates, but CPU intensive)
Typegen running on save (TS updates when you save the file, similar to if you were running a CLI)

**Comment by with-heart** [comment]
> Typegen running on save (TS updates when you save the file, similar to if you were running a CLI)

This would be perfect! Having `jest --watch` re-run the tests every time I type a few letters is not ideal 😁

**Comment by raghavraman** [comment]
👋  Any updates on this. Would greatly benefit from the save the file option. Thanks

**Comment by Andarist** [comment]
I believe that this is being fixed by https://github.com/statelyai/xstate-tools/pull/220 because with the changes in that PR we only update the typegen files when their output changes.
