### ISSUE TITLE
Supporting inline cond/action implementations?

### ISSUE THREAD

**Issue by lewisl9029** [statelyai/xstate-tools#57]
Hi there! Started a new project with xstate recently and have been really enjoying the experience!

Though I'm a bit disappointed with not being able to use the visualizer/editor due to my use of inline conds/actions. I find that the indirection from string-based conds/actions adds too much friction to be worthwhile for my use case where I have no need to ever serialize the machine config (are there other benefits that I'm missing?).

I originally assumed this is because the editor needs to serialize the machine to read and edit it, but recently learned it's actually smarter than that and works with the AST directly, in which case I'd love to learn more about what actual blockers are there to supporting inline implementations.

Throwing some random thoughts out there:

- If it's more feasible to support the visualization side without the editing side, I can totally live with that!

- Could an alternative API for providing inline implementations help? Maybe something that accepted an object with id instead of a function so it can be visualized with the id?

Please excuse my ignorance if these are things y'all have already thought about (which I assume is very likely the case 😅 ).

**Comment by mattpocock** [comment]
@lewisl9029 Currently the only blocker is time/energy - so thanks for shouting for this! The louder you shout, the faster we can head towards supporting it.

**Comment by mattpocock** [comment]
Closing, added in 1.7.1
