### ISSUE TITLE
Visual Editor erases "description" field on states

### ISSUE THREAD

**Issue by r-moore** [statelyai/xstate-tools#60]
The visual editor allows you add description field:

![image](https://user-images.githubusercontent.com/366280/153749834-8faa0d2d-9a29-4e99-8372-d70df845e310.png)
![image](https://user-images.githubusercontent.com/366280/153749842-5c5fe369-2f7a-4232-938a-e0b68c261979.png)

But when you close and reopen the editor the description is gone:
![image](https://user-images.githubusercontent.com/366280/153749864-abaac46d-f4f6-4feb-962a-ab7a76ecb6f8.png)

Furthermore as soon as you make any change to the statechart in the visual editor the description is erased from the machine definition

**Comment by mattpocock** [comment]
Fixed in latest version! Thanks all for your contributions!
