### ISSUE TITLE
Add VSCode extension to Open VSX Registry

### ISSUE THREAD

**Issue by laurakalbag** [statelyai/xstate-tools#67]
Distributing the VSCode extension to the [Open VSX Registry](https://open-vsx.org) would make the extension available to Codium, Coder and Gitpod users, as well as other code editors using VSCode-compatible extensions.

- [Open VSX Registry](https://open-vsx.org)
- [Open VSX Registry FAQ](https://www.eclipse.org/legal/open-vsx-registry-faq/)
- [Wiki on Publishing Extensions](https://github.com/eclipse/openvsx/wiki/Publishing-Extensions)

**Comment by mattpocock** [comment]
👍  Looks self-explanatory, consider this ticket in progress.

**Comment by mattpocock** [comment]
Deployed!
